/*
 * Webhook API
 *
 * Welcome to the Webhook API.
 *
 * The version of the OpenAPI document: 8.11.0
 * Contact: hello@apideck.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Apideck.Webhook.Client.OpenAPIDateConverter;

namespace Apideck.Webhook.Model
{
    /// <summary>
    /// Defines WebhookEventType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WebhookEventType
    {
        /// <summary>
        /// Enum Star for value: *
        /// </summary>
        [EnumMember(Value = "*")]
        Star = 1,

        /// <summary>
        /// Enum CrmActivityCreated for value: crm.activity.created
        /// </summary>
        [EnumMember(Value = "crm.activity.created")]
        CrmActivityCreated = 2,

        /// <summary>
        /// Enum CrmActivityUpdated for value: crm.activity.updated
        /// </summary>
        [EnumMember(Value = "crm.activity.updated")]
        CrmActivityUpdated = 3,

        /// <summary>
        /// Enum CrmActivityDeleted for value: crm.activity.deleted
        /// </summary>
        [EnumMember(Value = "crm.activity.deleted")]
        CrmActivityDeleted = 4,

        /// <summary>
        /// Enum CrmCompanyCreated for value: crm.company.created
        /// </summary>
        [EnumMember(Value = "crm.company.created")]
        CrmCompanyCreated = 5,

        /// <summary>
        /// Enum CrmCompanyUpdated for value: crm.company.updated
        /// </summary>
        [EnumMember(Value = "crm.company.updated")]
        CrmCompanyUpdated = 6,

        /// <summary>
        /// Enum CrmCompanyDeleted for value: crm.company.deleted
        /// </summary>
        [EnumMember(Value = "crm.company.deleted")]
        CrmCompanyDeleted = 7,

        /// <summary>
        /// Enum CrmContactCreated for value: crm.contact.created
        /// </summary>
        [EnumMember(Value = "crm.contact.created")]
        CrmContactCreated = 8,

        /// <summary>
        /// Enum CrmContactUpdated for value: crm.contact.updated
        /// </summary>
        [EnumMember(Value = "crm.contact.updated")]
        CrmContactUpdated = 9,

        /// <summary>
        /// Enum CrmContactDeleted for value: crm.contact.deleted
        /// </summary>
        [EnumMember(Value = "crm.contact.deleted")]
        CrmContactDeleted = 10,

        /// <summary>
        /// Enum CrmLeadCreated for value: crm.lead.created
        /// </summary>
        [EnumMember(Value = "crm.lead.created")]
        CrmLeadCreated = 11,

        /// <summary>
        /// Enum CrmLeadUpdated for value: crm.lead.updated
        /// </summary>
        [EnumMember(Value = "crm.lead.updated")]
        CrmLeadUpdated = 12,

        /// <summary>
        /// Enum CrmLeadDeleted for value: crm.lead.deleted
        /// </summary>
        [EnumMember(Value = "crm.lead.deleted")]
        CrmLeadDeleted = 13,

        /// <summary>
        /// Enum CrmNoteCreated for value: crm.note.created
        /// </summary>
        [EnumMember(Value = "crm.note.created")]
        CrmNoteCreated = 14,

        /// <summary>
        /// Enum CrmNotesUpdated for value: crm.notes.updated
        /// </summary>
        [EnumMember(Value = "crm.notes.updated")]
        CrmNotesUpdated = 15,

        /// <summary>
        /// Enum CrmNotesDeleted for value: crm.notes.deleted
        /// </summary>
        [EnumMember(Value = "crm.notes.deleted")]
        CrmNotesDeleted = 16,

        /// <summary>
        /// Enum CrmOpportunityCreated for value: crm.opportunity.created
        /// </summary>
        [EnumMember(Value = "crm.opportunity.created")]
        CrmOpportunityCreated = 17,

        /// <summary>
        /// Enum CrmOpportunityUpdated for value: crm.opportunity.updated
        /// </summary>
        [EnumMember(Value = "crm.opportunity.updated")]
        CrmOpportunityUpdated = 18,

        /// <summary>
        /// Enum CrmOpportunityDeleted for value: crm.opportunity.deleted
        /// </summary>
        [EnumMember(Value = "crm.opportunity.deleted")]
        CrmOpportunityDeleted = 19,

        /// <summary>
        /// Enum LeadLeadCreated for value: lead.lead.created
        /// </summary>
        [EnumMember(Value = "lead.lead.created")]
        LeadLeadCreated = 20,

        /// <summary>
        /// Enum LeadLeadUpdated for value: lead.lead.updated
        /// </summary>
        [EnumMember(Value = "lead.lead.updated")]
        LeadLeadUpdated = 21,

        /// <summary>
        /// Enum LeadLeadDeleted for value: lead.lead.deleted
        /// </summary>
        [EnumMember(Value = "lead.lead.deleted")]
        LeadLeadDeleted = 22,

        /// <summary>
        /// Enum VaultConnectionCreated for value: vault.connection.created
        /// </summary>
        [EnumMember(Value = "vault.connection.created")]
        VaultConnectionCreated = 23,

        /// <summary>
        /// Enum VaultConnectionUpdated for value: vault.connection.updated
        /// </summary>
        [EnumMember(Value = "vault.connection.updated")]
        VaultConnectionUpdated = 24,

        /// <summary>
        /// Enum VaultConnectionDeleted for value: vault.connection.deleted
        /// </summary>
        [EnumMember(Value = "vault.connection.deleted")]
        VaultConnectionDeleted = 25,

        /// <summary>
        /// Enum VaultConnectionCallable for value: vault.connection.callable
        /// </summary>
        [EnumMember(Value = "vault.connection.callable")]
        VaultConnectionCallable = 26,

        /// <summary>
        /// Enum AtsJobCreated for value: ats.job.created
        /// </summary>
        [EnumMember(Value = "ats.job.created")]
        AtsJobCreated = 27,

        /// <summary>
        /// Enum AtsJobUpdated for value: ats.job.updated
        /// </summary>
        [EnumMember(Value = "ats.job.updated")]
        AtsJobUpdated = 28,

        /// <summary>
        /// Enum AtsJobDeleted for value: ats.job.deleted
        /// </summary>
        [EnumMember(Value = "ats.job.deleted")]
        AtsJobDeleted = 29,

        /// <summary>
        /// Enum AtsApplicantCreated for value: ats.applicant.created
        /// </summary>
        [EnumMember(Value = "ats.applicant.created")]
        AtsApplicantCreated = 30,

        /// <summary>
        /// Enum AtsApplicantUpdated for value: ats.applicant.updated
        /// </summary>
        [EnumMember(Value = "ats.applicant.updated")]
        AtsApplicantUpdated = 31,

        /// <summary>
        /// Enum AtsApplicantDeleted for value: ats.applicant.deleted
        /// </summary>
        [EnumMember(Value = "ats.applicant.deleted")]
        AtsApplicantDeleted = 32,

        /// <summary>
        /// Enum PosOrderCreated for value: pos.order.created
        /// </summary>
        [EnumMember(Value = "pos.order.created")]
        PosOrderCreated = 33,

        /// <summary>
        /// Enum PosOrderUpdated for value: pos.order.updated
        /// </summary>
        [EnumMember(Value = "pos.order.updated")]
        PosOrderUpdated = 34,

        /// <summary>
        /// Enum PosOrderDeleted for value: pos.order.deleted
        /// </summary>
        [EnumMember(Value = "pos.order.deleted")]
        PosOrderDeleted = 35

    }

}
