/*
 * Webhook API
 *
 * Welcome to the Webhook API.
 *
 * The version of the OpenAPI document: 8.11.0
 * Contact: hello@apideck.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Apideck.Webhook.Client;
using Apideck.Webhook.Model;

namespace Apideck.Webhook.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List event logs
        /// </summary>
        /// <remarks>
        /// List event logs
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="filter">Filter results (optional)</param>
        /// <returns>GetWebhookEventLogsResponse</returns>
        GetWebhookEventLogsResponse EventLogsAll(string xApideckAppId, string cursor = default(string), int? limit = default(int?), WebhookEventLogsFilter filter = default(WebhookEventLogsFilter));

        /// <summary>
        /// List event logs
        /// </summary>
        /// <remarks>
        /// List event logs
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="filter">Filter results (optional)</param>
        /// <returns>ApiResponse of GetWebhookEventLogsResponse</returns>
        ApiResponse<GetWebhookEventLogsResponse> EventLogsAllWithHttpInfo(string xApideckAppId, string cursor = default(string), int? limit = default(int?), WebhookEventLogsFilter filter = default(WebhookEventLogsFilter));
        /// <summary>
        /// Create webhook
        /// </summary>
        /// <remarks>
        /// Create webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="createWebhookRequest"></param>
        /// <returns>CreateWebhookResponse</returns>
        CreateWebhookResponse WebhooksAdd(string xApideckAppId, CreateWebhookRequest createWebhookRequest);

        /// <summary>
        /// Create webhook
        /// </summary>
        /// <remarks>
        /// Create webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="createWebhookRequest"></param>
        /// <returns>ApiResponse of CreateWebhookResponse</returns>
        ApiResponse<CreateWebhookResponse> WebhooksAddWithHttpInfo(string xApideckAppId, CreateWebhookRequest createWebhookRequest);
        /// <summary>
        /// List webhooks
        /// </summary>
        /// <remarks>
        /// List webhooks
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <returns>GetWebhooksResponse</returns>
        GetWebhooksResponse WebhooksAll(string xApideckAppId, string cursor = default(string), int? limit = default(int?));

        /// <summary>
        /// List webhooks
        /// </summary>
        /// <remarks>
        /// List webhooks
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <returns>ApiResponse of GetWebhooksResponse</returns>
        ApiResponse<GetWebhooksResponse> WebhooksAllWithHttpInfo(string xApideckAppId, string cursor = default(string), int? limit = default(int?));
        /// <summary>
        /// Delete webhook
        /// </summary>
        /// <remarks>
        /// Delete webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <returns>DeleteWebhookResponse</returns>
        DeleteWebhookResponse WebhooksDelete(string id, string xApideckAppId);

        /// <summary>
        /// Delete webhook
        /// </summary>
        /// <remarks>
        /// Delete webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <returns>ApiResponse of DeleteWebhookResponse</returns>
        ApiResponse<DeleteWebhookResponse> WebhooksDeleteWithHttpInfo(string id, string xApideckAppId);
        /// <summary>
        /// Execute a webhook
        /// </summary>
        /// <remarks>
        /// Execute a webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="serviceId">Service provider ID.</param>
        /// <param name="body"></param>
        /// <returns>ExecuteWebhookResponse</returns>
        ExecuteWebhookResponse WebhooksExecute(string id, string serviceId, object body);

        /// <summary>
        /// Execute a webhook
        /// </summary>
        /// <remarks>
        /// Execute a webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="serviceId">Service provider ID.</param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of ExecuteWebhookResponse</returns>
        ApiResponse<ExecuteWebhookResponse> WebhooksExecuteWithHttpInfo(string id, string serviceId, object body);
        /// <summary>
        /// Get webhook
        /// </summary>
        /// <remarks>
        /// Get webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <returns>GetWebhookResponse</returns>
        GetWebhookResponse WebhooksOne(string id, string xApideckAppId);

        /// <summary>
        /// Get webhook
        /// </summary>
        /// <remarks>
        /// Get webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <returns>ApiResponse of GetWebhookResponse</returns>
        ApiResponse<GetWebhookResponse> WebhooksOneWithHttpInfo(string id, string xApideckAppId);
        /// <summary>
        /// Update webhook
        /// </summary>
        /// <remarks>
        /// Update webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="updateWebhookRequest"></param>
        /// <returns>UpdateWebhookResponse</returns>
        UpdateWebhookResponse WebhooksUpdate(string id, string xApideckAppId, UpdateWebhookRequest updateWebhookRequest);

        /// <summary>
        /// Update webhook
        /// </summary>
        /// <remarks>
        /// Update webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="updateWebhookRequest"></param>
        /// <returns>ApiResponse of UpdateWebhookResponse</returns>
        ApiResponse<UpdateWebhookResponse> WebhooksUpdateWithHttpInfo(string id, string xApideckAppId, UpdateWebhookRequest updateWebhookRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// List event logs
        /// </summary>
        /// <remarks>
        /// List event logs
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="filter">Filter results (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetWebhookEventLogsResponse</returns>
        System.Threading.Tasks.Task<GetWebhookEventLogsResponse> EventLogsAllAsync(string xApideckAppId, string cursor = default(string), int? limit = default(int?), WebhookEventLogsFilter filter = default(WebhookEventLogsFilter), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List event logs
        /// </summary>
        /// <remarks>
        /// List event logs
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="filter">Filter results (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetWebhookEventLogsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetWebhookEventLogsResponse>> EventLogsAllWithHttpInfoAsync(string xApideckAppId, string cursor = default(string), int? limit = default(int?), WebhookEventLogsFilter filter = default(WebhookEventLogsFilter), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Create webhook
        /// </summary>
        /// <remarks>
        /// Create webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="createWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateWebhookResponse</returns>
        System.Threading.Tasks.Task<CreateWebhookResponse> WebhooksAddAsync(string xApideckAppId, CreateWebhookRequest createWebhookRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create webhook
        /// </summary>
        /// <remarks>
        /// Create webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="createWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateWebhookResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateWebhookResponse>> WebhooksAddWithHttpInfoAsync(string xApideckAppId, CreateWebhookRequest createWebhookRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List webhooks
        /// </summary>
        /// <remarks>
        /// List webhooks
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetWebhooksResponse</returns>
        System.Threading.Tasks.Task<GetWebhooksResponse> WebhooksAllAsync(string xApideckAppId, string cursor = default(string), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List webhooks
        /// </summary>
        /// <remarks>
        /// List webhooks
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetWebhooksResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetWebhooksResponse>> WebhooksAllWithHttpInfoAsync(string xApideckAppId, string cursor = default(string), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete webhook
        /// </summary>
        /// <remarks>
        /// Delete webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteWebhookResponse</returns>
        System.Threading.Tasks.Task<DeleteWebhookResponse> WebhooksDeleteAsync(string id, string xApideckAppId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete webhook
        /// </summary>
        /// <remarks>
        /// Delete webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteWebhookResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeleteWebhookResponse>> WebhooksDeleteWithHttpInfoAsync(string id, string xApideckAppId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Execute a webhook
        /// </summary>
        /// <remarks>
        /// Execute a webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="serviceId">Service provider ID.</param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExecuteWebhookResponse</returns>
        System.Threading.Tasks.Task<ExecuteWebhookResponse> WebhooksExecuteAsync(string id, string serviceId, object body, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Execute a webhook
        /// </summary>
        /// <remarks>
        /// Execute a webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="serviceId">Service provider ID.</param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExecuteWebhookResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExecuteWebhookResponse>> WebhooksExecuteWithHttpInfoAsync(string id, string serviceId, object body, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get webhook
        /// </summary>
        /// <remarks>
        /// Get webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetWebhookResponse</returns>
        System.Threading.Tasks.Task<GetWebhookResponse> WebhooksOneAsync(string id, string xApideckAppId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get webhook
        /// </summary>
        /// <remarks>
        /// Get webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetWebhookResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetWebhookResponse>> WebhooksOneWithHttpInfoAsync(string id, string xApideckAppId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update webhook
        /// </summary>
        /// <remarks>
        /// Update webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="updateWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateWebhookResponse</returns>
        System.Threading.Tasks.Task<UpdateWebhookResponse> WebhooksUpdateAsync(string id, string xApideckAppId, UpdateWebhookRequest updateWebhookRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update webhook
        /// </summary>
        /// <remarks>
        /// Update webhook
        /// </remarks>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="updateWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateWebhookResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateWebhookResponse>> WebhooksUpdateWithHttpInfoAsync(string id, string xApideckAppId, UpdateWebhookRequest updateWebhookRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApi : IWebhooksApiSync, IWebhooksApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WebhooksApi : IWebhooksApi
    {
        private Apideck.Webhook.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WebhooksApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WebhooksApi(string basePath)
        {
            this.Configuration = Apideck.Webhook.Client.Configuration.MergeConfigurations(
                Apideck.Webhook.Client.GlobalConfiguration.Instance,
                new Apideck.Webhook.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Apideck.Webhook.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Apideck.Webhook.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Apideck.Webhook.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WebhooksApi(Apideck.Webhook.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Apideck.Webhook.Client.Configuration.MergeConfigurations(
                Apideck.Webhook.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Apideck.Webhook.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Apideck.Webhook.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Apideck.Webhook.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public WebhooksApi(Apideck.Webhook.Client.ISynchronousClient client, Apideck.Webhook.Client.IAsynchronousClient asyncClient, Apideck.Webhook.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Apideck.Webhook.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Apideck.Webhook.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Apideck.Webhook.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Apideck.Webhook.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Apideck.Webhook.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// List event logs List event logs
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="filter">Filter results (optional)</param>
        /// <returns>GetWebhookEventLogsResponse</returns>
        public GetWebhookEventLogsResponse EventLogsAll(string xApideckAppId, string cursor = default(string), int? limit = default(int?), WebhookEventLogsFilter filter = default(WebhookEventLogsFilter))
        {
            Apideck.Webhook.Client.ApiResponse<GetWebhookEventLogsResponse> localVarResponse = EventLogsAllWithHttpInfo(xApideckAppId, cursor, limit, filter);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List event logs List event logs
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="filter">Filter results (optional)</param>
        /// <returns>ApiResponse of GetWebhookEventLogsResponse</returns>
        public Apideck.Webhook.Client.ApiResponse<GetWebhookEventLogsResponse> EventLogsAllWithHttpInfo(string xApideckAppId, string cursor = default(string), int? limit = default(int?), WebhookEventLogsFilter filter = default(WebhookEventLogsFilter))
        {
            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->EventLogsAll");
            }

            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (filter != null)
            {
                if (filter.ExcludeApis != null)
                {
                    localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "filter[exclude_apis]", filter.ExcludeApis));
                }
                if (filter.Service != null)
                {
                    localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "filter[service]", filter.Service));
                }
                if (filter.ConsumerId != null)
                {
                    localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "filter[consumer_id]", filter.ConsumerId));
                }
                if (filter.EntityType != null)
                {
                    localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "filter[entity_type]", filter.EntityType));
                }
                if (filter.EventType != null)
                {
                    localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "filter[event_type]", filter.EventType));
                }
            }
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetWebhookEventLogsResponse>("/webhook/logs", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EventLogsAll", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List event logs List event logs
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="filter">Filter results (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetWebhookEventLogsResponse</returns>
        public async System.Threading.Tasks.Task<GetWebhookEventLogsResponse> EventLogsAllAsync(string xApideckAppId, string cursor = default(string), int? limit = default(int?), WebhookEventLogsFilter filter = default(WebhookEventLogsFilter), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Apideck.Webhook.Client.ApiResponse<GetWebhookEventLogsResponse> localVarResponse = await EventLogsAllWithHttpInfoAsync(xApideckAppId, cursor, limit, filter, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List event logs List event logs
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="filter">Filter results (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetWebhookEventLogsResponse)</returns>
        public async System.Threading.Tasks.Task<Apideck.Webhook.Client.ApiResponse<GetWebhookEventLogsResponse>> EventLogsAllWithHttpInfoAsync(string xApideckAppId, string cursor = default(string), int? limit = default(int?), WebhookEventLogsFilter filter = default(WebhookEventLogsFilter), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->EventLogsAll");
            }


            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetWebhookEventLogsResponse>("/webhook/logs", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EventLogsAll", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create webhook Create webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="createWebhookRequest"></param>
        /// <returns>CreateWebhookResponse</returns>
        public CreateWebhookResponse WebhooksAdd(string xApideckAppId, CreateWebhookRequest createWebhookRequest)
        {
            Apideck.Webhook.Client.ApiResponse<CreateWebhookResponse> localVarResponse = WebhooksAddWithHttpInfo(xApideckAppId, createWebhookRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create webhook Create webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="createWebhookRequest"></param>
        /// <returns>ApiResponse of CreateWebhookResponse</returns>
        public Apideck.Webhook.Client.ApiResponse<CreateWebhookResponse> WebhooksAddWithHttpInfo(string xApideckAppId, CreateWebhookRequest createWebhookRequest)
        {
            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksAdd");
            }

            // verify the required parameter 'createWebhookRequest' is set
            if (createWebhookRequest == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'createWebhookRequest' when calling WebhooksApi->WebhooksAdd");
            }

            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter
            localVarRequestOptions.Data = createWebhookRequest;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateWebhookResponse>("/webhook/webhooks", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksAdd", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create webhook Create webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="createWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateWebhookResponse</returns>
        public async System.Threading.Tasks.Task<CreateWebhookResponse> WebhooksAddAsync(string xApideckAppId, CreateWebhookRequest createWebhookRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Apideck.Webhook.Client.ApiResponse<CreateWebhookResponse> localVarResponse = await WebhooksAddWithHttpInfoAsync(xApideckAppId, createWebhookRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create webhook Create webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="createWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateWebhookResponse)</returns>
        public async System.Threading.Tasks.Task<Apideck.Webhook.Client.ApiResponse<CreateWebhookResponse>> WebhooksAddWithHttpInfoAsync(string xApideckAppId, CreateWebhookRequest createWebhookRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksAdd");
            }

            // verify the required parameter 'createWebhookRequest' is set
            if (createWebhookRequest == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'createWebhookRequest' when calling WebhooksApi->WebhooksAdd");
            }


            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter
            localVarRequestOptions.Data = createWebhookRequest;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateWebhookResponse>("/webhook/webhooks", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksAdd", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List webhooks List webhooks
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <returns>GetWebhooksResponse</returns>
        public GetWebhooksResponse WebhooksAll(string xApideckAppId, string cursor = default(string), int? limit = default(int?))
        {
            Apideck.Webhook.Client.ApiResponse<GetWebhooksResponse> localVarResponse = WebhooksAllWithHttpInfo(xApideckAppId, cursor, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List webhooks List webhooks
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <returns>ApiResponse of GetWebhooksResponse</returns>
        public Apideck.Webhook.Client.ApiResponse<GetWebhooksResponse> WebhooksAllWithHttpInfo(string xApideckAppId, string cursor = default(string), int? limit = default(int?))
        {
            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksAll");
            }

            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetWebhooksResponse>("/webhook/webhooks", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksAll", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List webhooks List webhooks
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetWebhooksResponse</returns>
        public async System.Threading.Tasks.Task<GetWebhooksResponse> WebhooksAllAsync(string xApideckAppId, string cursor = default(string), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Apideck.Webhook.Client.ApiResponse<GetWebhooksResponse> localVarResponse = await WebhooksAllWithHttpInfoAsync(xApideckAppId, cursor, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List webhooks List webhooks
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cursor">Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response. (optional)</param>
        /// <param name="limit">Number of records to return (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetWebhooksResponse)</returns>
        public async System.Threading.Tasks.Task<Apideck.Webhook.Client.ApiResponse<GetWebhooksResponse>> WebhooksAllWithHttpInfoAsync(string xApideckAppId, string cursor = default(string), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksAll");
            }


            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Apideck.Webhook.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetWebhooksResponse>("/webhook/webhooks", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksAll", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete webhook Delete webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <returns>DeleteWebhookResponse</returns>
        public DeleteWebhookResponse WebhooksDelete(string id, string xApideckAppId)
        {
            Apideck.Webhook.Client.ApiResponse<DeleteWebhookResponse> localVarResponse = WebhooksDeleteWithHttpInfo(id, xApideckAppId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete webhook Delete webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <returns>ApiResponse of DeleteWebhookResponse</returns>
        public Apideck.Webhook.Client.ApiResponse<DeleteWebhookResponse> WebhooksDeleteWithHttpInfo(string id, string xApideckAppId)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksDelete");
            }

            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksDelete");
            }

            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Apideck.Webhook.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<DeleteWebhookResponse>("/webhook/webhooks/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete webhook Delete webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteWebhookResponse</returns>
        public async System.Threading.Tasks.Task<DeleteWebhookResponse> WebhooksDeleteAsync(string id, string xApideckAppId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Apideck.Webhook.Client.ApiResponse<DeleteWebhookResponse> localVarResponse = await WebhooksDeleteWithHttpInfoAsync(id, xApideckAppId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete webhook Delete webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteWebhookResponse)</returns>
        public async System.Threading.Tasks.Task<Apideck.Webhook.Client.ApiResponse<DeleteWebhookResponse>> WebhooksDeleteWithHttpInfoAsync(string id, string xApideckAppId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksDelete");
            }

            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksDelete");
            }


            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Apideck.Webhook.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<DeleteWebhookResponse>("/webhook/webhooks/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Execute a webhook Execute a webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="serviceId">Service provider ID.</param>
        /// <param name="body"></param>
        /// <returns>ExecuteWebhookResponse</returns>
        public ExecuteWebhookResponse WebhooksExecute(string id, string serviceId, object body)
        {
            Apideck.Webhook.Client.ApiResponse<ExecuteWebhookResponse> localVarResponse = WebhooksExecuteWithHttpInfo(id, serviceId, body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Execute a webhook Execute a webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="serviceId">Service provider ID.</param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of ExecuteWebhookResponse</returns>
        public Apideck.Webhook.Client.ApiResponse<ExecuteWebhookResponse> WebhooksExecuteWithHttpInfo(string id, string serviceId, object body)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksExecute");
            }

            // verify the required parameter 'serviceId' is set
            if (serviceId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'serviceId' when calling WebhooksApi->WebhooksExecute");
            }

            // verify the required parameter 'body' is set
            if (body == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'body' when calling WebhooksApi->WebhooksExecute");
            }

            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Apideck.Webhook.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("serviceId", Apideck.Webhook.Client.ClientUtils.ParameterToString(serviceId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ExecuteWebhookResponse>("/webhook/webhooks/{id}/execute/{serviceId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksExecute", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Execute a webhook Execute a webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="serviceId">Service provider ID.</param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExecuteWebhookResponse</returns>
        public async System.Threading.Tasks.Task<ExecuteWebhookResponse> WebhooksExecuteAsync(string id, string serviceId, object body, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Apideck.Webhook.Client.ApiResponse<ExecuteWebhookResponse> localVarResponse = await WebhooksExecuteWithHttpInfoAsync(id, serviceId, body, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Execute a webhook Execute a webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="serviceId">Service provider ID.</param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExecuteWebhookResponse)</returns>
        public async System.Threading.Tasks.Task<Apideck.Webhook.Client.ApiResponse<ExecuteWebhookResponse>> WebhooksExecuteWithHttpInfoAsync(string id, string serviceId, object body, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksExecute");
            }

            // verify the required parameter 'serviceId' is set
            if (serviceId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'serviceId' when calling WebhooksApi->WebhooksExecute");
            }

            // verify the required parameter 'body' is set
            if (body == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'body' when calling WebhooksApi->WebhooksExecute");
            }


            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Apideck.Webhook.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("serviceId", Apideck.Webhook.Client.ClientUtils.ParameterToString(serviceId)); // path parameter
            localVarRequestOptions.Data = body;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ExecuteWebhookResponse>("/webhook/webhooks/{id}/execute/{serviceId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksExecute", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get webhook Get webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <returns>GetWebhookResponse</returns>
        public GetWebhookResponse WebhooksOne(string id, string xApideckAppId)
        {
            Apideck.Webhook.Client.ApiResponse<GetWebhookResponse> localVarResponse = WebhooksOneWithHttpInfo(id, xApideckAppId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get webhook Get webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <returns>ApiResponse of GetWebhookResponse</returns>
        public Apideck.Webhook.Client.ApiResponse<GetWebhookResponse> WebhooksOneWithHttpInfo(string id, string xApideckAppId)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksOne");
            }

            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksOne");
            }

            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Apideck.Webhook.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetWebhookResponse>("/webhook/webhooks/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksOne", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get webhook Get webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetWebhookResponse</returns>
        public async System.Threading.Tasks.Task<GetWebhookResponse> WebhooksOneAsync(string id, string xApideckAppId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Apideck.Webhook.Client.ApiResponse<GetWebhookResponse> localVarResponse = await WebhooksOneWithHttpInfoAsync(id, xApideckAppId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get webhook Get webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetWebhookResponse)</returns>
        public async System.Threading.Tasks.Task<Apideck.Webhook.Client.ApiResponse<GetWebhookResponse>> WebhooksOneWithHttpInfoAsync(string id, string xApideckAppId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksOne");
            }

            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksOne");
            }


            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Apideck.Webhook.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetWebhookResponse>("/webhook/webhooks/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksOne", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update webhook Update webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="updateWebhookRequest"></param>
        /// <returns>UpdateWebhookResponse</returns>
        public UpdateWebhookResponse WebhooksUpdate(string id, string xApideckAppId, UpdateWebhookRequest updateWebhookRequest)
        {
            Apideck.Webhook.Client.ApiResponse<UpdateWebhookResponse> localVarResponse = WebhooksUpdateWithHttpInfo(id, xApideckAppId, updateWebhookRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update webhook Update webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="updateWebhookRequest"></param>
        /// <returns>ApiResponse of UpdateWebhookResponse</returns>
        public Apideck.Webhook.Client.ApiResponse<UpdateWebhookResponse> WebhooksUpdateWithHttpInfo(string id, string xApideckAppId, UpdateWebhookRequest updateWebhookRequest)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksUpdate");
            }

            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksUpdate");
            }

            // verify the required parameter 'updateWebhookRequest' is set
            if (updateWebhookRequest == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'updateWebhookRequest' when calling WebhooksApi->WebhooksUpdate");
            }

            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Apideck.Webhook.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter
            localVarRequestOptions.Data = updateWebhookRequest;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<UpdateWebhookResponse>("/webhook/webhooks/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksUpdate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update webhook Update webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="updateWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateWebhookResponse</returns>
        public async System.Threading.Tasks.Task<UpdateWebhookResponse> WebhooksUpdateAsync(string id, string xApideckAppId, UpdateWebhookRequest updateWebhookRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Apideck.Webhook.Client.ApiResponse<UpdateWebhookResponse> localVarResponse = await WebhooksUpdateWithHttpInfoAsync(id, xApideckAppId, updateWebhookRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update webhook Update webhook
        /// </summary>
        /// <exception cref="Apideck.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.</param>
        /// <param name="xApideckAppId">The ID of your Unify application</param>
        /// <param name="updateWebhookRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateWebhookResponse)</returns>
        public async System.Threading.Tasks.Task<Apideck.Webhook.Client.ApiResponse<UpdateWebhookResponse>> WebhooksUpdateWithHttpInfoAsync(string id, string xApideckAppId, UpdateWebhookRequest updateWebhookRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksUpdate");
            }

            // verify the required parameter 'xApideckAppId' is set
            if (xApideckAppId == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'xApideckAppId' when calling WebhooksApi->WebhooksUpdate");
            }

            // verify the required parameter 'updateWebhookRequest' is set
            if (updateWebhookRequest == null)
            {
                throw new Apideck.Webhook.Client.ApiException(400, "Missing required parameter 'updateWebhookRequest' when calling WebhooksApi->WebhooksUpdate");
            }


            Apideck.Webhook.Client.RequestOptions localVarRequestOptions = new Apideck.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Apideck.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Apideck.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Apideck.Webhook.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("x-apideck-app-id", Apideck.Webhook.Client.ClientUtils.ParameterToString(xApideckAppId)); // header parameter
            localVarRequestOptions.Data = updateWebhookRequest;

            // authentication (apiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<UpdateWebhookResponse>("/webhook/webhooks/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksUpdate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
